### ISSUE TITLE
signature mismatch, build throws

### ISSUE THREAD

**Issue by Celuni** [Manolo8/DarkBOT#17]
Hey, I just wanted to note that the signature of the verifier.jar in github doesn't match with the base64 of POPCORN_PUB, build throws.

fixed by taking verifier.jar from discord stable downloads

why not just use sha-256?

**Comment by Pablete1234** [comment]
Tbh the "lib" folder isn't very reliable. Dll was outdated for months there, and verifier now seems to be. I'll update it later today but always refer to the one provided in the discord builds anyways.

The reason not to use sha-256 is that what we want to check is the file was signed by me, not that it's a specific version with a specific hash. Any version that is signed should work as long as it's compatible.
