### ISSUE TITLE
mouseClick bug

### ISSUE THREAD

**Issue by Celuni** [Manolo8/DarkBOT#18]
There is an issue with the dll native where it would hold down the mouse button and never releases. (I know we don't have the source of dll)

Fixed by replacing the native import with:

//public native void mouseClick(int x, int y);
public void mouseClick(int x, int y) {
    this.mousePress(x, y);
    this.mouseRelease(x, y);
}

**Comment by Pablete1234** [comment]
I have not seen this issue occur in normal behaviour of the bot.
