### ISSUE TITLE
Tempoary fix for "You are not close to the jump gate"

### ISSUE THREAD

**Issue by Celuni** [Manolo8/DarkBOT#19]
This bug is related to desync, the client believes we are on that coordinate but the server knows better, to fix this we have to input at least one other movement command. Since I'm hella lazy to find out if it's really only one or more movement commands to fix this I just spam drive.moves in the middle of the jump gate.

File: SafetyFinder.java in tick() switch (jumpState)

>case JUMPING:
>                 prevMap = hero.map;
>                 drive.stop(false);
>                 LocationInfo desyncFix = safety.entity.locationInfo;
>                 desyncFix.now.x = desyncFix.now.x + (int)(100.0 * Math.random());
>                 desyncFix.now.y = desyncFix.now.y + (int)(100.0 * Math.random());
>                 desyncFix.now.x = desyncFix.now.x - (int)(100.0 * Math.random());
>                 desyncFix.now.y = desyncFix.now.y - (int)(100.0 * Math.random());
>                 drive.move(desyncFix.now.x, desyncFix.now.y);
>                 hero.jumpPortal((Portal) safety.entity);
>                 return false;

Since I'm auto selling my cargo I jump a lot of gates per day, this fix is definitely working, you might not like my approach, feel free to change it to just one move, but I try to change as little as possible to get the result I want, I just want to get this fixed for everybody.

**Comment by Pablete1234** [comment]
This isn't new, and i've been aware of the issue for a long time. Spamming click isn't a solution, anyways it won't be an issue in the new browser anyways.
