### ISSUE TITLE
problem whit code

### ISSUE THREAD

**Issue by fabio1999ita** [Manolo8/DarkBOT#2]
when i git in intelliJ there are too error in code, why?

**Comment by Manolo8** [comment]
try again now

**Comment by fabio1999ita** [comment]
it doesn't work

**Comment by Manolo8** [comment]
Open Intellij IDEA
->
Goto maven
->
Press install
(will generate an .jar without meta-inf, but ignore the .jar)
->
Goto com.github.manolo8.darkbot.Bot
->
In the green button, press run Bot.main();
Will give an error, and will be added that:
![image](https://user-images.githubusercontent.com/13694982/52241483-fe7ace80-28ba-11e9-939f-03c155744a0a.png)
Open, click Edit configurations, in VM  options,  write it:
-Djava.library.path=./lib
![image](https://user-images.githubusercontent.com/13694982/52241535-2407d800-28bb-11e9-9895-0a4adeb0c410.png)
->
Press OK and RUN or DEBUG again

**Comment by fabio1999ita** [comment]
it work now thx

**Comment by DjangoLC** [comment]
Hi @Manolo8 I have the same issue, and I have already the setup that you post, can you help me please?

Intelliji setup: 
![image](https://user-images.githubusercontent.com/33673744/74110487-9eb0a680-4b52-11ea-810e-cd1de4950170.png)

and the console error: 
![image](https://user-images.githubusercontent.com/33673744/74110491-ac662c00-4b52-11ea-8311-3ddbf5ea9dac.png)
