### ISSUE TITLE
bot don't stop to move ship when it is in stop

### ISSUE THREAD

**Issue by fabio1999ita** [Manolo8/DarkBOT#3]
i have add that string in MainGui.java (line 118):
`Main.hero.drive.move(hero.locationInfo.now);`
and i have change varible `hero` in Main.java to static

the bot will no longer move after pressing the button to stop it
![image](https://user-images.githubusercontent.com/27001568/52294924-cf2b9680-297a-11e9-83ef-2086a4297593.png)

**Comment by Pablete1234** [comment]
Issues on github are to report problems in the source code of this repository, not the issues with your code.

**Comment by fabio1999ita** [comment]
in fact it is a problem of the code, I have also posted the resolution... read also tittle of issues

**Comment by Pablete1234** [comment]
The bot continuing to move after being stopped isn't a bug. Also your fix is defining behaviour changes on a GUI component, wich makes no sense.

**Comment by fabio1999ita** [comment]
if you stop bot and it continue to move to its position is a problem... if you can fix it better, do it
